---
version: '2'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=krtopi
      - MONGO_INITDB_ROOT_PASSWORD=krtopi
    ports:
    - "27017:27017"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'krtopi'
      MYSQL_USER: 'krtopi'
      MYSQL_PASSWORD: 'krtopi'
      MYSQL_ROOT_PASSWORD: 'krtopi'
    ports:
      - '3307:3306'
    expose:
      - '3306'